<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>Resources\micIco.ico</ApplicationIcon>
        <Platforms>x64</Platforms>
        <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
        <Company>LukaRepos</Company>
        <Product>VoiceSynth</Product>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ConseqConcatenation" Version="1.0.5" />
        <PackageReference Include="NAudio" Version="2.2.1" />
        <PackageReference Include="System.Speech" Version="11.0.0-preview.1.26104.118" />
    </ItemGroup>

    <ItemGroup>
        <!-- Иконка приложения -->
        <None Remove="Resources\micIco.ico" />
        <Content Include="Resources\micIco.ico">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Resources\micImage.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>

        <!-- Файл настроек -->
        <Content Include="settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>

        <!-- Piper TTS: все файлы рекурсивно, структура папок сохраняется -->
        <Content Include="piper\**\*" Condition="Exists('piper')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>piper\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>
    </ItemGroup>

</Project>
